services:
  db:
    image: postgres:14-alpine
    container_name: blog_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=blogdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./logs/db:/var/log/postgresql
    ports:
      - "5432:5432"
    restart: always

  api:
    build: .
    container_name: blog_api
    depends_on:
      - db
    ports:
      - "8080:8000"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=blogdb
    volumes:
      - ./logs/app:/app/logs
    restart: always

volumes:
  postgres_data: